### ISSUE TITLE
Couldn't download MODIS Aerosol product(MOD04_3K, MOD04_L2)

### ISSUE THREAD

**Issue by gajananQuantela** [jgomezdans/get_modis#12]
I tried this script to download MODIS Aerosol product, but I'm getting this error:

![getmodiserror](https://user-images.githubusercontent.com/34058577/35724896-5cf556e0-0825-11e8-8011-b65e7271d9a8.png)

I used this command:
./get_modis.py -v -p MOD04_3K.006 -s MOLT -y 2017 -t h25v07 -o /tmp/ -b 153 -e 155

**Comment by jgomezdans** [comment]
Hi, 
this tool doesn't consider the MODIS atmospheric parameters (they're on a different server, currently [this one](https://ladsweb.modaps.eosdis.nasa.gov)), only the land ones. Also, MOD04_3K isn't projected (e.g. no tile). I don't use these products myself, so haven't investigated them a lot.
