### ISSUE TITLE
Download is failing

### ISSUE THREAD

**Issue by sylar11** [jgomezdans/get_modis#17]
I don't know if this repo is still maintained but I'm getting this error:

./get_modis.py -s MOLT -u myuser -P mypaswd -p MOD09GA.061 -t h18v04 -y 2022 -b 223 -e 224 -o ./ -v
https://e4ftl01.cr.usgs.gov/MOLT/MOD09GA.061/
('them_urls', [])
<Response [401]>
Traceback (most recent call last):
File "./get_modis.py", line 327, in
get_xml=options.get_xml)
File "./get_modis.py", line 258, in get_modisfiles
raise IOError("Can't start download... [%s]" % the_url)
IOError: Can't start download... [https://e4ftl01.cr.usgs.gov/MOLT/MOD09GA.061//2022.08.11/MOD09GA.A2022223.h18v04.061.2022225035300.hdf]

any suggestions?

**Comment by jgomezdans** [comment]
Hi,
Please check new release just out. It should work now.
