### ISSUE TITLE
XML files not getting downloaded along HDF files

### ISSUE THREAD

**Issue by kalxas** [jgomezdans/get_modis#7]
Is there a specific reason for not downloading the xml files?

**Comment by jgomezdans** [comment]
I haven't really tested this, as I have no need for metadata files, so please test that commit. Cheers

**Comment by kalxas** [comment]
Thank you :)

**Comment by jgomezdans** [comment]
@kalxas  It appears that there were bugs in my last commit regarding downloading XML files, I think they've been solved now.
